---
- name: Create exporter dir 
  ansible.builtin.file:
    path: "{{ compose_host_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_host_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart docker-compose



